import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import { AuthProvider } from './providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DrinkStore XYZ',
  description: 'Generated by Simon Rothgang',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="flex flex-col min-h-screen max-w-[1260px] mx-auto">
          <AuthProvider>
            <Navbar />
            <div className="flex-1">
              {children}
            </div>
            <Footer />
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
